services:
  - type: web
    name: foodconnect-backend
    env: docker
    dockerContext: backend
    dockerfilePath: backend/Dockerfile
    plan: free
    region: oregon
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
